name: VPN Auto-Collector and Checker
on:
  schedule:
    - cron: '*/30 * * * *' # Запуск каждые 30 минут
  workflow_dispatch: # Ручной запуск

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Xray Checker
        run: |
          curl -sL -o - $(curl -s https://api.github.com/repos/kutovoys/xray-checker/releases/latest | grep "browser_download_url.*linux-amd64.tar.gz" | cut -d'"' -f4) | tar -xz
          chmod +x xray-checker

      - name: Collect Configs
        run: |
          > check.txt
          
          # Сбор Источника 1 - BLACK (пометка LTE)
          curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_VLESS_RUS_mobile.txt > s1.txt
          n=1
          while read -r line; do
            if [[ $line == vless://* ]]; then
              base=$(echo "$line" | cut -d'#' -f1)
              echo "${base}#🇷🇺 [LTE] №$n" >> check.txt
              n=$((n+1))
            fi
          done < s1.txt

          # Сбор Источника 2 - WHITE (пометка WI-FI)
          curl -s https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt > s2.txt
          n=1
          while read -r line; do
            if [[ $line == vless://* ]]; then
              base=$(echo "$line" | cut -d'#' -f1)
              echo "${base}#🌐 [WI-FI] №$n" >> check.txt
              n=$((n+1))
            fi
          done < s2.txt

      - name: Run Check
        run: |
          python3 -m http.server 8000 & 
          sleep 2
          ./xray-checker --subscription-url="http://localhost:8000/check.txt" --run-once > full_log.txt 2>&1

          echo "#profile-title: LLxickVPN" > results.txt
          echo "#profile-update-interval: 12" >> results.txt
          echo "#subscription-userinfo: total=0; expire=17837459931" >> results.txt
          echo "" >> results.txt

          grep "Success" full_log.txt | while read -r line; do
            proxy_name=$(echo "$line" | sed -E 's/^[0-9\/ :]* [0-9]{2}:[0-9]{2}:[0-9]{2} (.*) \| Success.*/\1/' | xargs)
            if [ ! -z "$proxy_name" ]; then
              grep -F "$proxy_name" check.txt >> results.txt || true
            fi
          done

      - name: Push results
        run: |
          git config --global user.name "VPN-Bot"
          git config --global user.email "bot@github.com"
          git add results.txt
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push